dist: focal    # Ubuntu 20.04
language: python
python:
  - "3.11"

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install black==23.7.0
  - pip install flake8
  - pip install coveralls

# Run before tests
before_script:
  - cd mysite
  - python manage.py migrate
  - python manage.py collectstatic --noinput

# Run tests
script:
  - black . --check
  - flake8 .
  - coverage run --source=polls manage.py test
  - coverage report

after_success:
  - coveralls

# Only build these branches
branches:
  only:
    - main