language: python
python:
  - "3.11"

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install black
  - pip install flake8

# Run before tests
before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

# Run tests
script:
  - black . --check
  - flake8 .
  - coverage run --source=polls manage.py test
  - coverage report

# Only build these branches
branches:
  only:
    - main