branch-defaults:
  default:
    environment: django-env
    group_suffix: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: cat-dog
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: second-account
  repository: null
  sc: null
  workspace_type: Application
